name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        browser: [electron, chrome, firefox]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Cache
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn

      - run: yarn build

      - run: yarn test:cypress --browser ${{ matrix.browser }}

      - run: yarn test:jest --coverage
        env:
          CI: true

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
